# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "TokenBrice personal blog: DeFi deep-dives and analyses"
weight = 1

[fr]
languageName = "French"
languagedirection = "ltr"
title = "TokenBrice Blog : analyses DeFi"
weight = 2
params =